//! Optional archive of included CSL styles.
//! This is the modified version and currently does not need to be generated via
//! tests/archive.rs.
// This file was originally generated by tests/archive.rs.

use std::sync::OnceLock;

use citationberg::taxonomy::Kind;
use citationberg::{LayoutRenderingElement, Locale, Style, TextTarget};
use serde::de::DeserializeOwned;

macro_rules! archived_style_bytes {
    ($name:literal) => {{
        include_bytes!(concat!(
            "../../archive/styles_zlib/",
            $name,
            ".cbor.zlib"
        )) as &[u8]
    }};
}

macro_rules! archived_locale_bytes {
    ($name:literal) => {{
        include_bytes!(concat!(
            "../../archive/locales_zlib/",
            $name,
            ".cbor.zlib"
        )) as &[u8]
    }};
}

/// An embedded CSL style.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum ArchivedStyle {
    /// ACS Guide 2022 revision.
    AmericanChemicalSociety,
    /// American Mathematical Society (label).
    AmericanMathematicalSocietyLabel,
    /// American Mathematical Society (numeric).
    AmericanMathematicalSocietyNumeric,
    /// AMA Manual of Style 11th edition.
    AmericanMedicalAssociation,
    /// American Physical Society.
    AmericanPhysicsSociety,
    /// APA Style 7th edition.
    AmericanPsychologicalAssociation,
    /// Association for Computing Machinery.
    AssociationForComputingMachinery,
    /// Chicago Manual of Style 18th edition (author-date).
    ChicagoAuthorDate,
    /// Elsevier (author-date/Harvard, with titles).
    ElsevierHarvard,
    /// Elsevier - NLM/Vancouver (citation-sequence).
    ElsevierVancouver,
    /// Elsevier (numeric, with titles).
    ElsevierWithTitles,
    /// China National Standard GB/T 7714-2015 (author-date, 中文).
    Gb77142015AuthorDate,
    /// China National Standard GB/T 7714-2015 (numeric, 中文).
    Gb77142015Numeric,
    /// Cite Them Right 12th edition (author-date/Harvard).
    HarvardCiteThemRight,
    /// IEEE Reference Guide version 11.29.2023.
    InstituteOfElectricalAndElectronicsEngineers,
    /// MLA Handbook 9th edition (in-text citations).
    ModernLanguageAssociation,
    /// Nature.
    Nature,
    /// NLM/Vancouver: Citing Medicine 2nd edition (citation-sequence).
    NlmCitationSequence,
    /// NLM/Vancouver: Citing Medicine 2nd edition (citation-sequence, superscript).
    NlmCitationSequenceSuperscript,
    /// Springer - Basic (numeric, brackets).
    SpringerBasic,
    /// Springer - Basic (author-date).
    SpringerBasicAuthorDate,
    /// Springer - NLM/Vancouver (citation-sequence, brackets).
    SpringerVancouver,
}

#[rustfmt::skip]
impl ArchivedStyle {
    /// Retrieve this style by name.
    pub fn by_name(name: &str) -> Option<Self> {
        match name {
            "american-chemical-society" => Some(Self::AmericanChemicalSociety),
            "american-mathematical-society-label" => Some(Self::AmericanMathematicalSocietyLabel),
            "american-mathematical-society-numeric" => Some(Self::AmericanMathematicalSocietyNumeric),
            "american-medical-association" => Some(Self::AmericanMedicalAssociation),
            "american-physics-society" => Some(Self::AmericanPhysicsSociety),
            "apa" => Some(Self::AmericanPsychologicalAssociation),
            "association-for-computing-machinery" => Some(Self::AssociationForComputingMachinery),
            "chicago-author-date" => Some(Self::ChicagoAuthorDate),
            "elsevier-harvard" => Some(Self::ElsevierHarvard),
            "elsevier-vancouver" => Some(Self::ElsevierVancouver),
            "elsevier-with-titles" => Some(Self::ElsevierWithTitles),
            "gb-7714-2015-author-date" => Some(Self::Gb77142015AuthorDate),
            "gb-7714-2015-numeric" => Some(Self::Gb77142015Numeric),
            "harvard-cite-them-right" => Some(Self::HarvardCiteThemRight),
            "ieee" => Some(Self::InstituteOfElectricalAndElectronicsEngineers),
            "mla" => Some(Self::ModernLanguageAssociation),
            "nature" => Some(Self::Nature),
            "vancouver" => Some(Self::NlmCitationSequence),
            "vancouver-superscript" => Some(Self::NlmCitationSequenceSuperscript),
            "springer-basic" => Some(Self::SpringerBasic),
            "springer-basic-author-date" => Some(Self::SpringerBasicAuthorDate),
            "springer-vancouver" => Some(Self::SpringerVancouver),
            _ => None,
        }
    }

    /// Retrieve this style by CSL ID.
    pub fn by_id(id: &str) -> Option<Self> {
        match id {
            "http://www.zotero.org/styles/american-chemical-society" => Some(Self::AmericanChemicalSociety),
            "http://www.zotero.org/styles/american-mathematical-society-label" => Some(Self::AmericanMathematicalSocietyLabel),
            "http://www.zotero.org/styles/american-mathematical-society-numeric" => Some(Self::AmericanMathematicalSocietyNumeric),
            "http://www.zotero.org/styles/american-medical-association" => Some(Self::AmericanMedicalAssociation),
            "http://www.zotero.org/styles/american-physics-society" => Some(Self::AmericanPhysicsSociety),
            "http://www.zotero.org/styles/apa" => Some(Self::AmericanPsychologicalAssociation),
            "http://www.zotero.org/styles/association-for-computing-machinery" => Some(Self::AssociationForComputingMachinery),
            "http://www.zotero.org/styles/chicago-author-date" => Some(Self::ChicagoAuthorDate),
            "http://www.zotero.org/styles/elsevier-harvard" => Some(Self::ElsevierHarvard),
            "http://www.zotero.org/styles/elsevier-vancouver" => Some(Self::ElsevierVancouver),
            "http://www.zotero.org/styles/elsevier-with-titles" => Some(Self::ElsevierWithTitles),
            "http://www.zotero.org/styles/china-national-standard-gb-t-7714-2015-author-date" => Some(Self::Gb77142015AuthorDate),
            "http://www.zotero.org/styles/china-national-standard-gb-t-7714-2015-numeric" => Some(Self::Gb77142015Numeric),
            "http://www.zotero.org/styles/harvard-cite-them-right" => Some(Self::HarvardCiteThemRight),
            "http://www.zotero.org/styles/ieee" => Some(Self::InstituteOfElectricalAndElectronicsEngineers),
            "http://www.zotero.org/styles/modern-language-association" => Some(Self::ModernLanguageAssociation),
            "http://www.zotero.org/styles/nature" => Some(Self::Nature),
            "http://www.zotero.org/styles/nlm-citation-sequence" => Some(Self::NlmCitationSequence),
            "http://www.zotero.org/styles/nlm-citation-sequence-superscript" => Some(Self::NlmCitationSequenceSuperscript),
            "http://www.zotero.org/styles/springer-basic-brackets" => Some(Self::SpringerBasic),
            "http://www.zotero.org/styles/springer-basic-author-date" => Some(Self::SpringerBasicAuthorDate),
            "http://www.zotero.org/styles/springer-vancouver-brackets" => Some(Self::SpringerVancouver),
            _ => None
        }
    }

    /// Returns all variants.
    pub fn all() -> &'static [Self] {
        &[
            Self::AmericanChemicalSociety,
            Self::AmericanMathematicalSocietyLabel,
            Self::AmericanMathematicalSocietyNumeric,
            Self::AmericanMedicalAssociation,
            Self::AmericanPhysicsSociety,
            Self::AmericanPsychologicalAssociation,
            Self::AssociationForComputingMachinery,
            Self::ChicagoAuthorDate,
            Self::ElsevierHarvard,
            Self::ElsevierVancouver,
            Self::ElsevierWithTitles,
            Self::Gb77142015AuthorDate,
            Self::Gb77142015Numeric,
            Self::HarvardCiteThemRight,
            Self::InstituteOfElectricalAndElectronicsEngineers,
            Self::ModernLanguageAssociation,
            Self::Nature,
            Self::NlmCitationSequence,
            Self::NlmCitationSequenceSuperscript,
            Self::SpringerBasic,
            Self::SpringerBasicAuthorDate,
            Self::SpringerVancouver,
        ]
    }

    /// Get the CBOR representation of this style.
    fn bytes(self) -> &'static [u8] {
        match self {
            Self::AmericanChemicalSociety => archived_style_bytes!("american-chemical-society"),
            Self::AmericanMathematicalSocietyLabel => archived_style_bytes!("american-mathematical-society-label"),
            Self::AmericanMathematicalSocietyNumeric => archived_style_bytes!("american-mathematical-society-numeric"),
            Self::AmericanMedicalAssociation => archived_style_bytes!("american-medical-association"),
            Self::AmericanPhysicsSociety => archived_style_bytes!("american-physics-society"),
            Self::AmericanPsychologicalAssociation => archived_style_bytes!("apa"),
            Self::AssociationForComputingMachinery => archived_style_bytes!("association-for-computing-machinery"),
            Self::ChicagoAuthorDate => archived_style_bytes!("chicago-author-date"),
            Self::ElsevierHarvard => archived_style_bytes!("elsevier-harvard"),
            Self::ElsevierVancouver => archived_style_bytes!("elsevier-vancouver"),
            Self::ElsevierWithTitles => archived_style_bytes!("elsevier-with-titles"),
            Self::Gb77142015AuthorDate => archived_style_bytes!("china-national-standard-gb-t-7714-2015-author-date"),
            Self::Gb77142015Numeric => archived_style_bytes!("china-national-standard-gb-t-7714-2015-numeric"),
            Self::HarvardCiteThemRight => archived_style_bytes!("harvard-cite-them-right"),
            Self::InstituteOfElectricalAndElectronicsEngineers => archived_style_bytes!("ieee"),
            Self::ModernLanguageAssociation => archived_style_bytes!("modern-language-association"),
            Self::Nature => archived_style_bytes!("nature"),
            Self::NlmCitationSequence => archived_style_bytes!("nlm-citation-sequence"),
            Self::NlmCitationSequenceSuperscript => archived_style_bytes!("nlm-citation-sequence-superscript"),
            Self::SpringerBasic => archived_style_bytes!("springer-basic-brackets"),
            Self::SpringerBasicAuthorDate => archived_style_bytes!("springer-basic-author-date"),
            Self::SpringerVancouver => archived_style_bytes!("springer-vancouver-brackets"),
        }
    }

    /// Retrieve the style.
    pub fn get(self) -> Style {
        let mut style = from_cbor(self.bytes()).unwrap();
        patch_style(self, &mut style);
        style
    }

    /// Get the style's names in Hayagriva.
    pub fn names(self) -> &'static [&'static str] {
        match self {
            Self::AmericanChemicalSociety => &[
                "american-chemical-society",
            ],
            Self::AmericanMathematicalSocietyLabel => &[
                "american-mathematical-society-label",
            ],
            Self::AmericanMathematicalSocietyNumeric => &[
                "american-mathematical-society-numeric",
            ],
            Self::AmericanMedicalAssociation => &[
                "american-medical-association",
            ],
            Self::AmericanPhysicsSociety => &[
                "american-physics-society",
            ],
            Self::AmericanPsychologicalAssociation => &[
                "apa",
            ],
            Self::AssociationForComputingMachinery => &[
                "association-for-computing-machinery",
            ],
            Self::ChicagoAuthorDate => &[
                "chicago-author-date",
            ],
            Self::ElsevierHarvard => &[
                "elsevier-harvard",
            ],
            Self::ElsevierVancouver => &[
                "elsevier-vancouver",
            ],
            Self::ElsevierWithTitles => &[
                "elsevier-with-titles",
            ],
            Self::Gb77142015AuthorDate => &[
                "gb-7714-2015-author-date",
            ],
            Self::Gb77142015Numeric => &[
                "gb-7714-2015-numeric",
            ],
            Self::HarvardCiteThemRight => &[
                "harvard-cite-them-right",
            ],
            Self::InstituteOfElectricalAndElectronicsEngineers => &[
                "ieee",
            ],
            Self::ModernLanguageAssociation => &[
                "mla",
            ],
            Self::Nature => &[
                "nature",
            ],
            Self::NlmCitationSequence => &[
                "vancouver",
            ],
            Self::NlmCitationSequenceSuperscript => &[
                "vancouver-superscript",
            ],
            Self::SpringerBasic => &[
                "springer-basic",
            ],
            Self::SpringerBasicAuthorDate => &[
                "springer-basic-author-date",
            ],
            Self::SpringerVancouver => &[
                "springer-vancouver",
            ],
        }
    }

    /// Get the style's full name.
    pub fn display_name(self) -> &'static str {
        match self {
            Self::AmericanChemicalSociety => "ACS Guide 2022 revision",
            Self::AmericanMathematicalSocietyLabel => "American Mathematical Society (label)",
            Self::AmericanMathematicalSocietyNumeric => "American Mathematical Society (numeric)",
            Self::AmericanMedicalAssociation => "AMA Manual of Style 11th edition",
            Self::AmericanPhysicsSociety => "American Physical Society",
            Self::AmericanPsychologicalAssociation => "APA Style 7th edition",
            Self::AssociationForComputingMachinery => "Association for Computing Machinery",
            Self::ChicagoAuthorDate => "Chicago Manual of Style 18th edition (author-date)",
            Self::ElsevierHarvard => "Elsevier (author-date/Harvard, with titles)",
            Self::ElsevierVancouver => "Elsevier - NLM/Vancouver (citation-sequence)",
            Self::ElsevierWithTitles => "Elsevier (numeric, with titles)",
            Self::Gb77142015AuthorDate => "China National Standard GB/T 7714-2015 (author-date, 中文)",
            Self::Gb77142015Numeric => "China National Standard GB/T 7714-2015 (numeric, 中文)",
            Self::HarvardCiteThemRight => "Cite Them Right 12th edition (author-date/Harvard)",
            Self::InstituteOfElectricalAndElectronicsEngineers => "IEEE Reference Guide version 11.29.2023",
            Self::ModernLanguageAssociation => "MLA Handbook 9th edition (in-text citations)",
            Self::Nature => "Nature",
            Self::NlmCitationSequence => "NLM/Vancouver: Citing Medicine 2nd edition (citation-sequence)",
            Self::NlmCitationSequenceSuperscript => "NLM/Vancouver: Citing Medicine 2nd edition (citation-sequence, superscript)",
            Self::SpringerBasic => "Springer - Basic (numeric, brackets)",
            Self::SpringerBasicAuthorDate => "Springer - Basic (author-date)",
            Self::SpringerVancouver => "Springer - NLM/Vancouver (citation-sequence, brackets)",
        }
    }

    /// Get the style's CSL ID.
    pub fn csl_id(self) -> &'static str {
        match self {
            Self::AmericanChemicalSociety => "http://www.zotero.org/styles/american-chemical-society",
            Self::AmericanMathematicalSocietyLabel => "http://www.zotero.org/styles/american-mathematical-society-label",
            Self::AmericanMathematicalSocietyNumeric => "http://www.zotero.org/styles/american-mathematical-society-numeric",
            Self::AmericanMedicalAssociation => "http://www.zotero.org/styles/american-medical-association",
            Self::AmericanPhysicsSociety => "http://www.zotero.org/styles/american-physics-society",
            Self::AmericanPsychologicalAssociation => "http://www.zotero.org/styles/apa",
            Self::AssociationForComputingMachinery => "http://www.zotero.org/styles/association-for-computing-machinery",
            Self::ChicagoAuthorDate => "http://www.zotero.org/styles/chicago-author-date",
            Self::ElsevierHarvard => "http://www.zotero.org/styles/elsevier-harvard",
            Self::ElsevierVancouver => "http://www.zotero.org/styles/elsevier-vancouver",
            Self::ElsevierWithTitles => "http://www.zotero.org/styles/elsevier-with-titles",
            Self::Gb77142015AuthorDate => "http://www.zotero.org/styles/china-national-standard-gb-t-7714-2015-author-date",
            Self::Gb77142015Numeric => "http://www.zotero.org/styles/china-national-standard-gb-t-7714-2015-numeric",
            Self::HarvardCiteThemRight => "http://www.zotero.org/styles/harvard-cite-them-right",
            Self::InstituteOfElectricalAndElectronicsEngineers => "http://www.zotero.org/styles/ieee",
            Self::ModernLanguageAssociation => "http://www.zotero.org/styles/modern-language-association",
            Self::Nature => "http://www.zotero.org/styles/nature",
            Self::NlmCitationSequence => "http://www.zotero.org/styles/nlm-citation-sequence",
            Self::NlmCitationSequenceSuperscript => "http://www.zotero.org/styles/nlm-citation-sequence-superscript",
            Self::SpringerBasic => "http://www.zotero.org/styles/springer-basic-brackets",
            Self::SpringerBasicAuthorDate => "http://www.zotero.org/styles/springer-basic-author-date",
            Self::SpringerVancouver => "http://www.zotero.org/styles/springer-vancouver-brackets",
        }
    }
}
fn decode_archive_bytes(reader: &[u8]) -> Result<Vec<u8>, String> {
    let mut decoder = zune_inflate::DeflateDecoder::new(reader);
    decoder
        .decode_zlib()
        .map_err(|err| format!("failed to decompress embedded archive entry: {err}"))
}

fn from_cbor<T: DeserializeOwned>(reader: &[u8]) -> Result<T, String> {
    let bytes = decode_archive_bytes(reader)?;
    ciborium::de::from_reader(bytes.as_slice())
        .map_err(|err| format!("failed to decode embedded archive entry: {err}"))
}

fn patch_style(archived: ArchivedStyle, style: &mut Style) {
    let Style::Independent(style) = style else {
        return;
    };

    match archived {
        ArchivedStyle::ElsevierHarvard => {
            let Some(bibliography) = style.bibliography.as_mut() else {
                return;
            };

            for element in &mut bibliography.layout.elements {
                let LayoutRenderingElement::Text(text) = element else {
                    continue;
                };

                if matches!(&text.target, TextTarget::Macro { name } if name == "access")
                    && text.affixes.prefix.as_deref() == Some(". ")
                {
                    text.affixes.prefix = Some(" ".to_string());
                }
            }
        }
        ArchivedStyle::SpringerVancouver => {
            if let Some(date_macro) = style.macros.iter_mut().find(|m| m.name == "date") {
                remove_macro_text(&mut date_macro.children, "accessed-date");
                clear_group_suffix_for_types(
                    &mut date_macro.children,
                    &[Kind::ArticleJournal, Kind::ArticleMagazine, Kind::ArticleNewspaper],
                    ";",
                );
            }
            if let Some(journal_location) =
                style.macros.iter_mut().find(|m| m.name == "journal-location")
            {
                prefix_text_variable(&mut journal_location.children, ";");
            }
        }
        _ => {}
    }
}

fn remove_macro_text(elements: &mut Vec<LayoutRenderingElement>, macro_name: &str) {
    elements.retain(|element| {
        !matches!(
            element,
            LayoutRenderingElement::Text(text)
                if matches!(&text.target, TextTarget::Macro { name } if name == macro_name)
        )
    });

    for element in elements {
        match element {
            LayoutRenderingElement::Group(group) => {
                remove_macro_text(&mut group.children, macro_name);
            }
            LayoutRenderingElement::Choose(choose) => {
                remove_macro_text(&mut choose.if_.children, macro_name);
                for branch in &mut choose.else_if {
                    remove_macro_text(&mut branch.children, macro_name);
                }
                if let Some(otherwise) = &mut choose.otherwise {
                    remove_macro_text(&mut otherwise.children, macro_name);
                }
            }
            _ => {}
        }
    }
}

fn clear_group_suffix_for_types(
    elements: &mut [LayoutRenderingElement],
    types: &[Kind],
    suffix: &str,
) {
    for element in elements {
        match element {
            LayoutRenderingElement::Choose(choose) => {
                for branch in std::iter::once(&mut choose.if_).chain(choose.else_if.iter_mut()) {
                    if branch
                        .type_
                        .as_ref()
                        .is_some_and(|branch_types| branch_types.iter().any(|t| types.contains(t)))
                    {
                        for child in &mut branch.children {
                            if let LayoutRenderingElement::Group(group) = child
                                && group.suffix.as_deref() == Some(suffix)
                            {
                                group.suffix = None;
                            }
                        }
                    }
                    clear_group_suffix_for_types(&mut branch.children, types, suffix);
                }

                if let Some(otherwise) = &mut choose.otherwise {
                    clear_group_suffix_for_types(&mut otherwise.children, types, suffix);
                }
            }
            LayoutRenderingElement::Group(group) => {
                clear_group_suffix_for_types(&mut group.children, types, suffix);
            }
            _ => {}
        }
    }
}

fn prefix_text_variable(elements: &mut [LayoutRenderingElement], prefix: &str) {
    for element in elements {
        match element {
            LayoutRenderingElement::Text(text)
                if matches!(&text.target, TextTarget::Variable { .. }) =>
            {
                text.affixes.prefix = Some(prefix.to_string());
            }
            LayoutRenderingElement::Group(group) => {
                prefix_text_variable(&mut group.children, prefix);
            }
            LayoutRenderingElement::Choose(choose) => {
                prefix_text_variable(&mut choose.if_.children, prefix);
                for branch in &mut choose.else_if {
                    prefix_text_variable(&mut branch.children, prefix);
                }
                if let Some(otherwise) = &mut choose.otherwise {
                    prefix_text_variable(&mut otherwise.children, prefix);
                }
            }
            _ => {}
        }
    }
}

/// CBOR-encoded CSL locales.
pub const LOCALES: &[&[u8]] = &[
    archived_locale_bytes!("de-DE"),
    archived_locale_bytes!("en-GB"),
    archived_locale_bytes!("en-US"),
    archived_locale_bytes!("es-ES"),
    archived_locale_bytes!("fr-FR"),
    archived_locale_bytes!("ja-JP"),
    archived_locale_bytes!("pt-BR"),
    archived_locale_bytes!("zh-CN"),
    archived_locale_bytes!("zh-TW"),
];

/// Get all CSL locales.
pub fn locales() -> Vec<Locale> {
    static LOCALE_CACHE: OnceLock<Vec<Locale>> = OnceLock::new();
    LOCALE_CACHE
        .get_or_init(|| {
            LOCALES
                .iter()
                .map(|bytes| from_cbor::<Locale>(bytes).unwrap())
                .collect()
        })
        .clone()
}
